spring.application.name=HospitalManagementSystem

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true
spring.datasource.username=Arashad
spring.datasource.password=Arashad@6139
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
# 15 minutes in milliseconds
jwt.expiration=900000
# 7 days in milliseconds
jwt.refresh-expiration=604800000
# Set to true in Production (HTTPS)
app.security.secure-cookie=false
# IMPORTANT: Use a strong secret in production (at least 256 bits). Must be Base64 encoded.
# Decodes to: ThisIsASecretKeyThatIsLongEnoughForHS256Algorithm
jwt.secret=VGhpc0lzQVNlY3JldEtleVGhhdElzTG9uZ0Vub3VnaEZvckhTMjU2QWxnb3JpdGht

